# Generated by Django 4.2.1 on 2023-05-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'can cancel order'), ('view_history', 'Can view history')]},
        ),
    ]
